SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
MASTER_VOLUME = 0.1

ASSET_PATH = 'assets/'
PLAYER1_IMG = ASSET_PATH + 'Player1.png'
PLAYER2_IMG = ASSET_PATH + 'Player2.png'
ENEMY_GROUND_IMG = ASSET_PATH + 'EnemyGround.png'
ENEMY_FLY_IMG = ASSET_PATH + 'EnemyFlying.png'
CAR_IMG = ASSET_PATH + 'Car.png'
PLAYER_SHOT_IMG = ASSET_PATH + 'PlayerShot.png'
ENEMY_SHOT_IMG = ASSET_PATH + 'EnemyShot.png'
BACKGROUND_IMG = ASSET_PATH + 'Background.png'
LIFE_HEART_IMG = ASSET_PATH + 'LifeHeart.png'
BACKGROUND_IMG_MENU = ASSET_PATH + 'BackgroundMenu.png'

SOUND_PATH = ASSET_PATH + 'sounds/'

MENU_MUSIC = SOUND_PATH + 'MenuMusic.mp3'
GAME_MUSIC = SOUND_PATH + 'GameMusic.mp3'
SHOOT_SOUND = SOUND_PATH + 'Shoot.mp3'
ENEMY_HIT_SOUND = SOUND_PATH + 'EnemyDeath.mp3'
PLAYER_HIT_SOUND = SOUND_PATH + 'PlayerHit.mp3'
HEART_PICK_SOUND = SOUND_PATH + 'HeartPick.mp3'
HEART_DROP_SOUND = SOUND_PATH + 'HeartDrop.mp3'
PLAYER_HURT_SOUND = SOUND_PATH + 'PlayerHurt.mp3'
GAME_START_SOUND = SOUND_PATH + 'GameStart.mp3'



PLAYER_SPEED = 5
SHOT_SPEED = 7
ENEMY_SPEED = 2
ENEMY_SHOT_SPEED = 4

SPAWN_INTERVAL = 2000
LIFE_INTERVAL = 30000  # ms between giving extra life
PLAYER_LIVES = 3

